// assets/app/stack/react/modules/vite/customization/CustomSocket.tsx
import { type ClassicPreset } from "rete";
import styled from "styled-components";
import { $socketsize } from "./vars";

const Styles = styled.div`
  display: inline-block;
  cursor: pointer;
  border: 1px solid grey;
  width: ${$socketsize}px;
  height: ${$socketsize * 2}px;
  vertical-align: middle;
  background: #fff;
  z-index: 2;
  box-sizing: border-box;
  &:hover {
    background: #ddd;
  }
`;

export function CustomSocket<T extends ClassicPreset.Socket>(props: {
  data: T;
}) {
  return <Styles title={props.data.name} />;
}

// assets/app/stack/svelte/modules/customization/CustomSocket.svelte
<script lang="ts">
  import type { ClassicPreset } from "rete";

  export let data: ClassicPreset.Socket;
</script>

<div class="socket" title={data.name} />

<style lang="scss" scoped>
  @use "sass:math";
  @import "./vars";

  .socket {
    display: inline-block;
    cursor: pointer;
    border: 1px solid grey;
    width: $socket-size;
    height: $socket-size * 2;
    vertical-align: middle;
    background: #fff;
    z-index: 2;
    box-sizing: border-box;

    &:hover {
      background: #ddd;
    }
  }
</style>
