// assets/app/stack/react/modules/vite/customization/CustomConnection.tsx
import styled from "styled-components";
import { type ClassicScheme, Presets } from "rete-react-plugin";

const { useConnection } = Presets.classic;

const Svg = styled.svg`
  overflow: visible !important;
  position: absolute;
  pointer-events: none;
  width: 9999px;
  height: 9999px;
`;

const Path = styled.path<{ styles?: (props: any) => any }>`
  fill: none;
  stroke-width: 5px;
  stroke: black;
  pointer-events: auto;
  ${(props) => props.styles && props.styles(props)}
`;

export function CustomConnection(props: {
  data: ClassicScheme["Connection"] & { isLoop?: boolean };
  styles?: () => any;
}) {
  const { path } = useConnection();

  if (!path) return null;

  return (
    <Svg data-testid="connection">
      <Path styles={props.styles} d={path} />
    </Svg>
  );
}

// assets/app/stack/svelte/modules/customization/CustomConnection.svelte
<script lang="ts">
  import type { ClassicScheme } from "rete-svelte-plugin";
  type Position = { x: number; y: number };

  // svelte-ignore unused-export-let
  export let data: ClassicScheme["Connection"] & { isLoop?: boolean };
  // svelte-ignore unused-export-let
  export let start: Position;
  // svelte-ignore unused-export-let
  export let end: Position;
  export let path: string;
</script>

<svg data-testid="connection">
  <path d={path} />
</svg>

<style>
  /*! https://github.com/retejs/connection-plugin/commit/206ca0fd7fb82801ac45a0f7180ae05dff9ed901 */
  svg {
    overflow: visible !important;
    position: absolute;
    pointer-events: none;
    width: 9999px;
    height: 9999px;
  }

  svg path {
    fill: none;
    stroke-width: 5px;
    stroke: black;
    pointer-events: auto;
  }
</style>
